DELETE FROM order_items;
DELETE FROM orders;
DELETE FROM products;

INSERT INTO products (
  id,
  parent_product_id,
  parent_product_name,
  slug,
  name,
  variant_name,
  description,
  category,
  price,
  compare_at_price,
  inventory,
  image_url,
  is_featured,
  sort_order,
  is_active,
  created_at,
  updated_at
)
VALUES
(
  'prod_lash_0',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-7-8mm-d-curl-0-3',
  'Lash Extensions 7-8mm D Curl 0.3',
  '7-8mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  0,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_1',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-9mm-d-curl-0-3',
  'Lash Extensions 9mm D Curl 0.3',
  '9 mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  1,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_2',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-10mm-d-curl-0-3',
  'Lash Extensions 10mm D Curl 0.3',
  '10 mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  2,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_3',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-11mm-d-curl-0-3',
  'Lash Extensions 11mm D Curl 0.3',
  '11mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  3,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_4',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-12mm-d-curl-0-3',
  'Lash Extensions 12mm D Curl 0.3',
  '12mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  4,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_5',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-13mm-d-curl-0-3',
  'Lash Extensions 13mm D Curl 0.3',
  '13mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  5,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_6',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-14mm-d-curl-0-3',
  'Lash Extensions 14mm D Curl 0.3',
  '14mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  6,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_7',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-15mm-d-curl-0-3',
  'Lash Extensions 15mm D Curl 0.3',
  '15mm d curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  120,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  7,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_8',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-12-15mm-d-curl-0-7',
  'Lash Extensions 12-15mm D Curl 0.7',
  '12-15mm d curl 0.7',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  95,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  8,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
),
(
  'prod_lash_9',
  'lash_extensions',
  'Lash Extensions',
  'lash-extensions-8-11mm-cc-curl-0-3',
  'Lash Extensions 8-11mm CC Curl 0.3',
  '8-11mm cc curl 0.3',
  'Premium lash extensions with multiple sizes and curls for a perfect, customizable look.',
  'Lashes',
  1500,
  NULL,
  95,
  'https://medusa-public-images.s3.eu-west-1.amazonaws.com/sweatshirt-vintage-front.png',
  1,
  9,
  1,
  strftime('%s','now') * 1000,
  strftime('%s','now') * 1000
);
